// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv3fM5FSN2PKPLCllDIQyzSRzhdiDX9lQ',
    appId: '1:53607531902:web:5bb3f8f58aebf0d8771f2f',
    messagingSenderId: '53607531902',
    projectId: 'projectx-223eb',
    authDomain: 'projectx-223eb.firebaseapp.com',
    storageBucket: 'projectx-223eb.appspot.com',
    measurementId: 'G-DFXQPLC5Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3tFWaa-7fuBzGV9z55NeQO5kmRdkI1U',
    appId: '1:53607531902:android:e8228b300c435141771f2f',
    messagingSenderId: '53607531902',
    projectId: 'projectx-223eb',
    storageBucket: 'projectx-223eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcRnBhOopPnH7r2aFm_3PAzL1eWQ5_Q4',
    appId: '1:53607531902:ios:665eb9dfe421e3d0771f2f',
    messagingSenderId: '53607531902',
    projectId: 'projectx-223eb',
    storageBucket: 'projectx-223eb.appspot.com',
    androidClientId: '53607531902-b6c7jg0pc6199d11d0nmvrtkips5kcrq.apps.googleusercontent.com',
    iosClientId: '53607531902-cgp8cng92k8b1qrgp3l5m3k1hjb90gog.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectxweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWcRnBhOopPnH7r2aFm_3PAzL1eWQ5_Q4',
    appId: '1:53607531902:ios:dd0b627129e4e369771f2f',
    messagingSenderId: '53607531902',
    projectId: 'projectx-223eb',
    storageBucket: 'projectx-223eb.appspot.com',
    androidClientId: '53607531902-b6c7jg0pc6199d11d0nmvrtkips5kcrq.apps.googleusercontent.com',
    iosClientId: '53607531902-ko07piecjp0r8tcr5ajf1o4ebj6kgg3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectxweb.RunnerTests',
  );
}
